function pct(n){return n.toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})}
function badgeClass(p){return p==='PRIORITÁRIA'?'pri':p==='COMPLEMENTAR'?'comp':'res'}
function tempFor(c){return c>=2?['QUENTE','hot']:c===1?['MORNO','warm']:['FRIO','cold']}
function isExtra(s){return /histórico|extra-programa/i.test(s)}
function inferDifficulty(t){t=t.toLowerCase();const hard=['ecocardi','espirometr','medicina fetal','transplante','oncogen','forest plot','kaplan','molecular','massa cervical','cabeça e pescoço','mediastino','retina','mielopatia','desmieliniz','hipófise','periampular','neoplasias hepáticas','hipertensão portal'];const easy=['genograma','níveis de prevenção','lesões elementares','amenorreia','ovários policísticos','infertilidade','tuberculose','litíase','hpb','diverticular','asma','microcristalinas','artrite reumatoide','avaliação pré-anestésica'];if(hard.some(x=>t.includes(x)))return'Difícil';if(easy.some(x=>t.includes(x)))return'Fácil–Médio';return'Médio'}
function roi(count,diff){if(count>=2&&diff!=='Difícil')return'MUITO ALTO';if(count>=1&&diff!=='Difícil')return'ALTO';if(count>=2)return'ALTO';if(count===1)return'MÉDIO';return diff==='Difícil'?'BAIXO':'MÉDIO–BAIXO'}
function buildMicro(){const out=[];disciplines.forEach(d=>(topicData[d.id]||[]).forEach(([topic,count])=>{if(count>0){const diff=inferDifficulty(topic),r=roi(count,diff);out.push({discipline:d.name,topic,count,diff,roi:r,include:r.includes('ALTO')?'SIM':'DEPOIS'})}}));return out}
function renderMacro(){const tb=document.getElementById('macroBody');tb.innerHTML='';disciplines.forEach(d=>{const tr=document.createElement('tr');tr.innerHTML=`<td><b>${d.name}</b><div class="bar"><i style="width:${Math.min(100,d.hist_pct*10)}%"></i></div></td><td>${d.hist} / 75</td><td>${pct(d.hist_pct)}%</td><td><span class="badge ${badgeClass(d.priority)}">${d.priority}</span></td><td><b>${pct(d.time)}%</b></td><td><select class="level" data-id="${d.id}"><option${d.level==='Fraco'?' selected':''}>Fraco</option><option${d.level==='Médio'?' selected':''}>Médio</option><option${d.level==='Forte'?' selected':''}>Forte</option></select></td><td>${d.status}</td>`;tb.appendChild(tr)});document.querySelectorAll('.level').forEach(el=>{const saved=localStorage.getItem('omed_level_'+el.dataset.id);if(saved)el.value=saved;el.addEventListener('change',()=>localStorage.setItem('omed_level_'+el.dataset.id,el.value))})}
function populateSelect(){const s=document.getElementById('disciplineSelect');s.innerHTML=disciplines.map(d=>`<option value="${d.id}">${d.name} — ${d.hist}/75</option>`).join('');s.value='pediatria';s.onchange=renderTopics;document.getElementById('tempFilter').onchange=renderTopics;renderTopics()}
function renderTopics(){const id=document.getElementById('disciplineSelect').value,f=document.getElementById('tempFilter').value,g=document.getElementById('topicGrid');g.innerHTML='';(topicData[id]||[]).forEach(([name,count])=>{const[temp,cl]=tempFor(count);if(f!=='all'&&f!==cl)return;const div=document.createElement('div');div.className='topic';div.innerHTML=`<div class="top"><b>${name}</b><span class="badge ${cl}">${temp}</span></div><small>${count} questão(ões) em 75 ${isExtra(name)?'• histórico extra':''}</small>`;g.appendChild(div)});if(!g.children.length)g.innerHTML='<div class="notice">Nenhum tópico neste filtro.</div>'}
function renderMicro(){const tb=document.getElementById('microBody');tb.innerHTML='';buildMicro().sort((a,b)=>b.count-a.count||a.discipline.localeCompare(b.discipline)).forEach(x=>{const cl=x.roi.includes('ALTO')?'roi-high':x.roi==='MÉDIO'?'roi-mid':'roi-low',tr=document.createElement('tr');tr.innerHTML=`<td>${x.discipline}</td><td><b>${x.topic}</b></td><td>${x.count} / 75</td><td>${x.diff}</td><td class="${cl}"><b>${x.roi}</b></td><td>${x.include}</td>`;tb.appendChild(tr)})}
function renderSchedule(){const box=document.getElementById('schedule'),done=JSON.parse(localStorage.getItem('omed_done')||'[]');box.innerHTML='';sessions.forEach((s,i)=>{const[date,title,activity,review]=s,div=document.createElement('div');div.className='day'+(done.includes(i)?' done':'');div.innerHTML=`<input class="check" type="checkbox" data-i="${i}" ${done.includes(i)?'checked':''}><div class="date">${date} • Sessão ${i+1}/28</div><h4>${title}</h4><p>${activity}</p><p><b>Revisão:</b> ${review}</p><div class="ratio"><span>36m teoria</span><span>60m questões</span><span>24m revisão</span></div>`;box.appendChild(div)});document.querySelectorAll('.check').forEach(c=>c.onchange=()=>{let a=JSON.parse(localStorage.getItem('omed_done')||'[]'),i=+c.dataset.i;if(c.checked&&!a.includes(i))a.push(i);if(!c.checked)a=a.filter(x=>x!==i);localStorage.setItem('omed_done',JSON.stringify(a));renderSchedule()})}
function resetProgress(){if(confirm('Zerar todas as sessões marcadas como concluídas?')){localStorage.removeItem('omed_done');renderSchedule()}}
function countdown(){const now=new Date(),exam=new Date('2026-09-19T14:00:00-03:00'),d=Math.max(0,Math.ceil((exam-now)/86400000));document.getElementById('countdown').textContent=d}
renderMacro();populateSelect();renderMicro();renderSchedule();countdown();